"""add text research tables

Revision ID: d8ddea885de9
Revises: 7f3c1a9d2e44
Create Date: 2026-09-06 13:43:51.609497

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8ddea885de9"
down_revision: str | Sequence[str] | None = "7f3c1a9d2e44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_codebooks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("is_frozen", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_codebooks_created_by"), "research_codebooks", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_research_codebooks_project_id"), "research_codebooks", ["project_id"], unique=False
    )
    op.create_table(
        "research_contextual_datasets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_contextual_datasets_project_id"),
        "research_contextual_datasets",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "research_corpora",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_corpora_created_by"), "research_corpora", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_research_corpora_project_id"), "research_corpora", ["project_id"], unique=False
    )
    op.create_table(
        "research_dictionaries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("terms_json", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_dictionaries_created_by"),
        "research_dictionaries",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_dictionaries_project_id"),
        "research_dictionaries",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "research_preprocessing_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("config_json", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_preprocessing_profiles_created_by"),
        "research_preprocessing_profiles",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_preprocessing_profiles_project_id"),
        "research_preprocessing_profiles",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "research_analysis_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("corpus_id", sa.String(), nullable=True),
        sa.Column("run_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress_stage", sa.String(length=64), nullable=True),
        sa.Column("parameters_json", sa.Text(), nullable=True),
        sa.Column("metrics_json", sa.Text(), nullable=True),
        sa.Column("results_json", sa.Text(), nullable=True),
        sa.Column("artifact_path", sa.String(length=1024), nullable=True),
        sa.Column("random_seed", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["research_corpora.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_analysis_runs_corpus_id"),
        "research_analysis_runs",
        ["corpus_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_analysis_runs_created_by"),
        "research_analysis_runs",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_analysis_runs_project_id"),
        "research_analysis_runs",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_analysis_runs_run_type"),
        "research_analysis_runs",
        ["run_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_analysis_runs_status"), "research_analysis_runs", ["status"], unique=False
    )
    op.create_table(
        "research_annotation_labels",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("codebook_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("inclusion_criteria", sa.Text(), nullable=True),
        sa.Column("exclusion_criteria", sa.Text(), nullable=True),
        sa.Column("positive_examples_json", sa.Text(), nullable=True),
        sa.Column("negative_examples_json", sa.Text(), nullable=True),
        sa.Column("is_placeholder", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["codebook_id"], ["research_codebooks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_annotation_labels_codebook_id"),
        "research_annotation_labels",
        ["codebook_id"],
        unique=False,
    )
    op.create_table(
        "research_contextual_observations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("dataset_id", sa.String(), nullable=False),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("values_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["research_contextual_datasets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_contextual_observations_country"),
        "research_contextual_observations",
        ["country"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_contextual_observations_dataset_id"),
        "research_contextual_observations",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_contextual_observations_year"),
        "research_contextual_observations",
        ["year"],
        unique=False,
    )
    op.create_table(
        "research_corpus_documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("corpus_id", sa.String(), nullable=False),
        sa.Column("rag_document_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("organization", sa.String(length=255), nullable=True),
        sa.Column("organization_type", sa.String(length=128), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("publication_type", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("region", sa.String(length=128), nullable=True),
        sa.Column("cultural_sphere", sa.String(length=128), nullable=True),
        sa.Column("language", sa.String(length=64), nullable=True),
        sa.Column("education_level", sa.String(length=128), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("research_notes", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["research_corpora.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rag_document_id"], ["rag_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("corpus_id", "rag_document_id", name="uq_corpus_rag_document"),
    )
    op.create_index(
        op.f("ix_research_corpus_documents_corpus_id"),
        "research_corpus_documents",
        ["corpus_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_corpus_documents_cultural_sphere"),
        "research_corpus_documents",
        ["cultural_sphere"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_corpus_documents_language"),
        "research_corpus_documents",
        ["language"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_corpus_documents_organization"),
        "research_corpus_documents",
        ["organization"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_corpus_documents_publication_type"),
        "research_corpus_documents",
        ["publication_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_corpus_documents_publication_year"),
        "research_corpus_documents",
        ["publication_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_corpus_documents_rag_document_id"),
        "research_corpus_documents",
        ["rag_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_corpus_documents_region"),
        "research_corpus_documents",
        ["region"],
        unique=False,
    )
    op.create_table(
        "research_training_dataset_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("corpus_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unit_type", sa.String(length=32), nullable=False),
        sa.Column("codebook_id", sa.String(), nullable=False),
        sa.Column("codebook_version", sa.String(length=64), nullable=False),
        sa.Column("annotation_source", sa.String(length=64), nullable=False),
        sa.Column("minimum_agreement", sa.Float(), nullable=True),
        sa.Column("unit_ids_json", sa.Text(), nullable=False),
        sa.Column("document_ids_json", sa.Text(), nullable=False),
        sa.Column("labels_json", sa.Text(), nullable=False),
        sa.Column("class_distribution_json", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["codebook_id"], ["research_codebooks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["corpus_id"], ["research_corpora.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_training_dataset_snapshots_codebook_id"),
        "research_training_dataset_snapshots",
        ["codebook_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_training_dataset_snapshots_corpus_id"),
        "research_training_dataset_snapshots",
        ["corpus_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_training_dataset_snapshots_created_by"),
        "research_training_dataset_snapshots",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_training_dataset_snapshots_project_id"),
        "research_training_dataset_snapshots",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "research_text_units",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("corpus_document_id", sa.String(), nullable=False),
        sa.Column("unit_type", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("paragraph_number", sa.Integer(), nullable=True),
        sa.Column("sentence_number", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["corpus_document_id"], ["research_corpus_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "corpus_document_id", "unit_type", "position", name="uq_text_unit_position"
        ),
    )
    op.create_index(
        op.f("ix_research_text_units_corpus_document_id"),
        "research_text_units",
        ["corpus_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_text_units_text_hash"), "research_text_units", ["text_hash"], unique=False
    )
    op.create_index(
        op.f("ix_research_text_units_unit_type"), "research_text_units", ["unit_type"], unique=False
    )
    op.create_table(
        "research_topic_labels",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("analysis_run_id", sa.String(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("human_name", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"], ["research_analysis_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_run_id", "topic_id", name="uq_topic_label_run_topic"),
    )
    op.create_index(
        op.f("ix_research_topic_labels_analysis_run_id"),
        "research_topic_labels",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_table(
        "research_trained_models",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("corpus_id", sa.String(), nullable=False),
        sa.Column("analysis_run_id", sa.String(), nullable=False),
        sa.Column("training_dataset_snapshot_id", sa.String(), nullable=False),
        sa.Column("model_family", sa.String(length=64), nullable=False),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("label_ids_json", sa.Text(), nullable=False),
        sa.Column("feature_config_json", sa.Text(), nullable=False),
        sa.Column("training_config_json", sa.Text(), nullable=False),
        sa.Column("metrics_json", sa.Text(), nullable=False),
        sa.Column("model_artifact_path", sa.String(length=1024), nullable=False),
        sa.Column("vectorizer_artifact_path", sa.String(length=1024), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"], ["research_analysis_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["corpus_id"], ["research_corpora.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["training_dataset_snapshot_id"],
            ["research_training_dataset_snapshots.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_trained_models_analysis_run_id"),
        "research_trained_models",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_trained_models_corpus_id"),
        "research_trained_models",
        ["corpus_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_trained_models_created_by"),
        "research_trained_models",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_trained_models_project_id"),
        "research_trained_models",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_trained_models_training_dataset_snapshot_id"),
        "research_trained_models",
        ["training_dataset_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "research_adjudications",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("text_unit_id", sa.String(), nullable=False),
        sa.Column("label_id", sa.String(), nullable=False),
        sa.Column("final_value", sa.String(length=32), nullable=False),
        sa.Column("adjudicator_id", sa.String(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["adjudicator_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["label_id"], ["research_annotation_labels.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["text_unit_id"], ["research_text_units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("text_unit_id", "label_id", name="uq_adjudication_unit_label"),
    )
    op.create_index(
        op.f("ix_research_adjudications_adjudicator_id"),
        "research_adjudications",
        ["adjudicator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_adjudications_label_id"),
        "research_adjudications",
        ["label_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_adjudications_text_unit_id"),
        "research_adjudications",
        ["text_unit_id"],
        unique=False,
    )
    op.create_table(
        "research_annotation_tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("text_unit_id", sa.String(), nullable=False),
        sa.Column("annotator_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["annotator_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["text_unit_id"], ["research_text_units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "text_unit_id", "annotator_id", name="uq_annotation_task_unit_annotator"
        ),
    )
    op.create_index(
        op.f("ix_research_annotation_tasks_annotator_id"),
        "research_annotation_tasks",
        ["annotator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_annotation_tasks_status"),
        "research_annotation_tasks",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_annotation_tasks_text_unit_id"),
        "research_annotation_tasks",
        ["text_unit_id"],
        unique=False,
    )
    op.create_table(
        "research_annotations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("text_unit_id", sa.String(), nullable=False),
        sa.Column("label_id", sa.String(), nullable=False),
        sa.Column("annotator_id", sa.String(), nullable=False),
        sa.Column("value", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("codebook_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["annotator_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["label_id"], ["research_annotation_labels.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["text_unit_id"], ["research_text_units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "text_unit_id",
            "label_id",
            "annotator_id",
            "codebook_version",
            name="uq_annotation_unit_label_annotator_version",
        ),
    )
    op.create_index(
        op.f("ix_research_annotations_annotator_id"),
        "research_annotations",
        ["annotator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_annotations_label_id"), "research_annotations", ["label_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_annotations_text_unit_id"),
        "research_annotations",
        ["text_unit_id"],
        unique=False,
    )
    op.create_table(
        "research_model_predictions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("trained_model_id", sa.String(), nullable=False),
        sa.Column("text_unit_id", sa.String(), nullable=False),
        sa.Column("predicted_labels_json", sa.Text(), nullable=False),
        sa.Column("scores_json", sa.Text(), nullable=False),
        sa.Column("uncertainty", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["text_unit_id"], ["research_text_units.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["trained_model_id"], ["research_trained_models.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trained_model_id", "text_unit_id", name="uq_prediction_model_unit"),
    )
    op.create_index(
        op.f("ix_research_model_predictions_text_unit_id"),
        "research_model_predictions",
        ["text_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_model_predictions_trained_model_id"),
        "research_model_predictions",
        ["trained_model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_model_predictions_uncertainty"),
        "research_model_predictions",
        ["uncertainty"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_research_model_predictions_uncertainty"), table_name="research_model_predictions"
    )
    op.drop_index(
        op.f("ix_research_model_predictions_trained_model_id"),
        table_name="research_model_predictions",
    )
    op.drop_index(
        op.f("ix_research_model_predictions_text_unit_id"), table_name="research_model_predictions"
    )
    op.drop_table("research_model_predictions")
    op.drop_index(op.f("ix_research_annotations_text_unit_id"), table_name="research_annotations")
    op.drop_index(op.f("ix_research_annotations_label_id"), table_name="research_annotations")
    op.drop_index(op.f("ix_research_annotations_annotator_id"), table_name="research_annotations")
    op.drop_table("research_annotations")
    op.drop_index(
        op.f("ix_research_annotation_tasks_text_unit_id"), table_name="research_annotation_tasks"
    )
    op.drop_index(
        op.f("ix_research_annotation_tasks_status"), table_name="research_annotation_tasks"
    )
    op.drop_index(
        op.f("ix_research_annotation_tasks_annotator_id"), table_name="research_annotation_tasks"
    )
    op.drop_table("research_annotation_tasks")
    op.drop_index(
        op.f("ix_research_adjudications_text_unit_id"), table_name="research_adjudications"
    )
    op.drop_index(op.f("ix_research_adjudications_label_id"), table_name="research_adjudications")
    op.drop_index(
        op.f("ix_research_adjudications_adjudicator_id"), table_name="research_adjudications"
    )
    op.drop_table("research_adjudications")
    op.drop_index(
        op.f("ix_research_trained_models_training_dataset_snapshot_id"),
        table_name="research_trained_models",
    )
    op.drop_index(
        op.f("ix_research_trained_models_project_id"), table_name="research_trained_models"
    )
    op.drop_index(
        op.f("ix_research_trained_models_created_by"), table_name="research_trained_models"
    )
    op.drop_index(
        op.f("ix_research_trained_models_corpus_id"), table_name="research_trained_models"
    )
    op.drop_index(
        op.f("ix_research_trained_models_analysis_run_id"), table_name="research_trained_models"
    )
    op.drop_table("research_trained_models")
    op.drop_index(
        op.f("ix_research_topic_labels_analysis_run_id"), table_name="research_topic_labels"
    )
    op.drop_table("research_topic_labels")
    op.drop_index(op.f("ix_research_text_units_unit_type"), table_name="research_text_units")
    op.drop_index(op.f("ix_research_text_units_text_hash"), table_name="research_text_units")
    op.drop_index(
        op.f("ix_research_text_units_corpus_document_id"), table_name="research_text_units"
    )
    op.drop_table("research_text_units")
    op.drop_index(
        op.f("ix_research_training_dataset_snapshots_project_id"),
        table_name="research_training_dataset_snapshots",
    )
    op.drop_index(
        op.f("ix_research_training_dataset_snapshots_created_by"),
        table_name="research_training_dataset_snapshots",
    )
    op.drop_index(
        op.f("ix_research_training_dataset_snapshots_corpus_id"),
        table_name="research_training_dataset_snapshots",
    )
    op.drop_index(
        op.f("ix_research_training_dataset_snapshots_codebook_id"),
        table_name="research_training_dataset_snapshots",
    )
    op.drop_table("research_training_dataset_snapshots")
    op.drop_index(
        op.f("ix_research_corpus_documents_region"), table_name="research_corpus_documents"
    )
    op.drop_index(
        op.f("ix_research_corpus_documents_rag_document_id"), table_name="research_corpus_documents"
    )
    op.drop_index(
        op.f("ix_research_corpus_documents_publication_year"),
        table_name="research_corpus_documents",
    )
    op.drop_index(
        op.f("ix_research_corpus_documents_publication_type"),
        table_name="research_corpus_documents",
    )
    op.drop_index(
        op.f("ix_research_corpus_documents_organization"), table_name="research_corpus_documents"
    )
    op.drop_index(
        op.f("ix_research_corpus_documents_language"), table_name="research_corpus_documents"
    )
    op.drop_index(
        op.f("ix_research_corpus_documents_cultural_sphere"), table_name="research_corpus_documents"
    )
    op.drop_index(
        op.f("ix_research_corpus_documents_corpus_id"), table_name="research_corpus_documents"
    )
    op.drop_table("research_corpus_documents")
    op.drop_index(
        op.f("ix_research_contextual_observations_year"),
        table_name="research_contextual_observations",
    )
    op.drop_index(
        op.f("ix_research_contextual_observations_dataset_id"),
        table_name="research_contextual_observations",
    )
    op.drop_index(
        op.f("ix_research_contextual_observations_country"),
        table_name="research_contextual_observations",
    )
    op.drop_table("research_contextual_observations")
    op.drop_index(
        op.f("ix_research_annotation_labels_codebook_id"), table_name="research_annotation_labels"
    )
    op.drop_table("research_annotation_labels")
    op.drop_index(op.f("ix_research_analysis_runs_status"), table_name="research_analysis_runs")
    op.drop_index(op.f("ix_research_analysis_runs_run_type"), table_name="research_analysis_runs")
    op.drop_index(op.f("ix_research_analysis_runs_project_id"), table_name="research_analysis_runs")
    op.drop_index(op.f("ix_research_analysis_runs_created_by"), table_name="research_analysis_runs")
    op.drop_index(op.f("ix_research_analysis_runs_corpus_id"), table_name="research_analysis_runs")
    op.drop_table("research_analysis_runs")
    op.drop_index(
        op.f("ix_research_preprocessing_profiles_project_id"),
        table_name="research_preprocessing_profiles",
    )
    op.drop_index(
        op.f("ix_research_preprocessing_profiles_created_by"),
        table_name="research_preprocessing_profiles",
    )
    op.drop_table("research_preprocessing_profiles")
    op.drop_index(op.f("ix_research_dictionaries_project_id"), table_name="research_dictionaries")
    op.drop_index(op.f("ix_research_dictionaries_created_by"), table_name="research_dictionaries")
    op.drop_table("research_dictionaries")
    op.drop_index(op.f("ix_research_corpora_project_id"), table_name="research_corpora")
    op.drop_index(op.f("ix_research_corpora_created_by"), table_name="research_corpora")
    op.drop_table("research_corpora")
    op.drop_index(
        op.f("ix_research_contextual_datasets_project_id"),
        table_name="research_contextual_datasets",
    )
    op.drop_table("research_contextual_datasets")
    op.drop_index(op.f("ix_research_codebooks_project_id"), table_name="research_codebooks")
    op.drop_index(op.f("ix_research_codebooks_created_by"), table_name="research_codebooks")
    op.drop_table("research_codebooks")
    # ### end Alembic commands ###
