import { Box, Chip, Divider, Skeleton, Stack, Tab, Tabs, Typography } from "@mui/material";
import { PlaylistAddCheck as TaskIcon, ViewKanban as BoardIcon, ViewList as ListIcon } from "@mui/icons-material";
import { alpha } from "@mui/material/styles";
import { EmptyState } from "../../../components/ui/EmptyState";
import { SectionCard } from "../../../components/ui/SectionCard";
import type { ProjectDetailModel } from "../hooks/useProjectDetail";
import { TASK_STATUS_OPTIONS, type TaskView } from "../projectTaskModel";
import { TaskBoardCard, TaskListCard } from "./ProjectTaskCards";

export function ProjectFlowSection({ model: m }: { model: ProjectDetailModel }) { return <SectionCard title="Project flow" description="Switch between a sortable Kanban board and a detailed list view." action={<Tabs value={m.taskView} onChange={(_, value: TaskView) => m.setTaskView(value)} sx={{ minHeight: "auto" }}><Tab value="board" icon={<BoardIcon fontSize="small" />} iconPosition="start" label="Board" /><Tab value="list" icon={<ListIcon fontSize="small" />} iconPosition="start" label="List" /></Tabs>}>
    {m.tasksQuery.isLoading ? <Stack spacing={1.5}><Skeleton variant="rounded" height={280} sx={{ borderRadius: 3 }} /><Skeleton variant="rounded" height={280} sx={{ borderRadius: 3 }} /></Stack> : m.orderedTasks.length === 0 ? <EmptyState icon={<TaskIcon />} title="No tasks yet" description="Create the first task to turn this project into an active delivery flow." /> : m.taskView === "list" ? <Stack spacing={1.5}>{m.orderedTasks.map((task) => <TaskListCard key={task.id} task={task} selected={task.id === m.selectedTaskId} onSelect={() => m.select(task)} />)}</Stack> :
    <Box sx={{ overflowX: { md: "auto" }, WebkitOverflowScrolling: "touch", pb: 1 }}><Box sx={{ display: "grid", gap: 1.5, minWidth: { md: 1280 }, gridTemplateColumns: { xs: "1fr", md: "repeat(5, minmax(240px, 1fr))" } }}>{TASK_STATUS_OPTIONS.map((option) => { const tasks = m.orderedTasks.filter((task) => task.status === option.value); return <Box key={option.value} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); m.drop(option.value); }} sx={(t) => ({ minHeight: 240, p: 1.25, borderRadius: 4, border: `1px solid ${t.palette.divider}`, backgroundColor: alpha(t.palette.background.paper, t.palette.mode === "dark" ? 0.82 : 0.72) })}><Stack spacing={1.25}><Stack direction="row" justifyContent="space-between"><Typography variant="subtitle2">{option.label}</Typography><Chip label={tasks.length} size="small" variant="outlined" /></Stack><Divider /><Stack spacing={1}>{tasks.length ? tasks.map((task) => <TaskBoardCard key={task.id} task={task} selected={task.id === m.selectedTaskId} isDragging={m.draggingTaskId === task.id} onSelect={() => m.select(task)} onDragStart={() => m.setDraggingTaskId(task.id)} onDropBefore={() => m.drop(option.value, task.id)} onMove={(status) => m.drop(status, undefined, task.id)} />) : <Box sx={(t) => ({ p: 2, borderRadius: 3, border: `1px dashed ${t.palette.divider}`, textAlign: "center", color: "text.secondary" })}><Typography variant="body2">Drop tasks here</Typography></Box>}</Stack></Stack></Box>; })}</Box></Box>}
</SectionCard>; }
