import { apiFetch, apiFetchStream, type Paginated } from "../client";
import type {
    AnalysisRun,
    Annotation,
    AnnotationBlindPolicy,
    AnnotationCampaign,
    AnnotationLabel,
    AnnotationMode,
    AnnotationProgress,
    AnnotationQueueItem,
    Codebook,
    CorpusDocument,
    CleaningPreview,
    CleaningProfile,
    DashboardSummary,
    DatasetPreview,
    ExportManifest,
    PreprocessingProfile,
    ResearchCorpus,
    ResearchMemo,
    TrainedModel,
    TrainingDatasetSnapshot,
    IngestionQaDocument,
    UnitType,
    UncertainPrediction,
} from "../../features/text-research/types";

export const BASE = "/research";

export { apiFetch, apiFetchStream };
export type { Paginated };
export type {
    AnalysisRun,
    Annotation,
    AnnotationBlindPolicy,
    AnnotationCampaign,
    AnnotationLabel,
    AnnotationMode,
    AnnotationProgress,
    AnnotationQueueItem,
    Codebook,
    CorpusDocument,
    CleaningPreview,
    CleaningProfile,
    DashboardSummary,
    DatasetPreview,
    ExportManifest,
    PreprocessingProfile,
    ResearchCorpus,
    ResearchMemo,
    TrainedModel,
    TrainingDatasetSnapshot,
    IngestionQaDocument,
    UnitType,
    UncertainPrediction,
};
