"""Quantitative / statistical / measurement request schemas.

Single source of truth lives in ``schemas.py`` (shared constants and richer
validators). This module re-exports those models for quantitative route imports
and for the ``api.schemas`` package layout (LATEST-017).
"""

from __future__ import annotations

from backend.modules.text_research.api.schemas import (
    MAX_CLUSTERS,
    MAX_COOCCURRENCE_WINDOW,
    MAX_EMBEDDING_DIMS,
    MAX_EMBEDDING_ITEMS,
    MAX_EMBEDDING_TOTAL_FLOATS,
    MAX_KWIC_MATCHES,
    MAX_KWIC_WINDOW,
    MAX_MEASUREMENT_VALUES,
    MAX_MINHASH_PERM,
    MAX_PAIRWISE_TOP_K,
    MAX_RESULT_TOP_N,
    MAX_STATISTICAL_INDEPENDENT_VARS,
    MAX_STATISTICAL_ROWS,
    MAX_SVD_COMPONENTS,
    AnalysisRequest,
    AsyncCapableAnalysisRequest,
    ClusteringRequest,
    CooccurrenceRequest,
    CorpusFilters,
    DfmRequest,
    DfmTrimConfig,
    DictionaryAnalysisRequest,
    DimensionalityReductionRequest,
    DuplicateDetectionRequest,
    FrequencyRequest,
    InlineAnalysisRequest,
    KeynessRequest,
    KwicRequest,
    MeasurementComparisonRequest,
    NgramRequest,
    ReadabilityRequest,
    SimilarityRequest,
    StatisticalModelRequest,
)

__all__ = [
    "MAX_RESULT_TOP_N",
    "MAX_PAIRWISE_TOP_K",
    "MAX_COOCCURRENCE_WINDOW",
    "MAX_KWIC_WINDOW",
    "MAX_KWIC_MATCHES",
    "MAX_CLUSTERS",
    "MAX_SVD_COMPONENTS",
    "MAX_MINHASH_PERM",
    "MAX_EMBEDDING_ITEMS",
    "MAX_EMBEDDING_DIMS",
    "MAX_EMBEDDING_TOTAL_FLOATS",
    "MAX_STATISTICAL_ROWS",
    "MAX_STATISTICAL_INDEPENDENT_VARS",
    "MAX_MEASUREMENT_VALUES",
    "CorpusFilters",
    "AnalysisRequest",
    "InlineAnalysisRequest",
    "AsyncCapableAnalysisRequest",
    "FrequencyRequest",
    "NgramRequest",
    "DfmTrimConfig",
    "DfmRequest",
    "KwicRequest",
    "DictionaryAnalysisRequest",
    "KeynessRequest",
    "CooccurrenceRequest",
    "SimilarityRequest",
    "DuplicateDetectionRequest",
    "ClusteringRequest",
    "DimensionalityReductionRequest",
    "ReadabilityRequest",
    "StatisticalModelRequest",
    "MeasurementComparisonRequest",
]
